### ISSUE TITLE
Check that socket is still connected before invoking next()

### ISSUE THREAD

**Issue by jondubois** [happilymarrieddad/sc-publish-out-queue#1]
Right now in MIDDLEWARE_PUBLISH_OUT, because `next()` is called asynchronously, it's possible that it might be invoked after the socket has become disconnected in  - So maybe there should be an additional check on `socket.state` to make sure that it's not disconnected before calling `next()`.

**Comment by happilymarrieddad** [comment]
that is a good point. Sorry, I've been on vacation and haven't been on github. I'll fix it and push now.

**Comment by happilymarrieddad** [comment]
0.2.2 - Fixed. Thanks!
